services:
  workday-api:
    build: .
    container_name: china-workday-api
    ports:
      - "8001:8000"
    volumes:
      - cache-data:/app/cache
    restart: always
    environment:
      - TZ=Asia/Shanghai

volumes:
  cache-data:
